<?php

namespace Database\Seeders;

use App\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $courses = [
            "Accounting", 
            "Actuarial Science", 
            "Advertising And Public Relations", 
            "Aerospace Engineering", 
            "Agricultural Economics", 
            "Agriculture Production And Management", 
            "Animal Sciences", 
            "Anthropology And Archeology", 
            "Applied Mathematics", 
            "Architectural Engineering", 
            "Architecture", 
            "Area Ethnic And Civilization Studies", 
            "Art And Music Education", 
            "Art History And Criticism", 
            "Astronomy And Astrophysics", 
            "Atmospheric Sciences And Meteorology", 
            "Biochemical Sciences", 
            "Biological Engineering", 
            "Biology", 
            "Biomedical Engineering", 
            "Botany", 
            "Business Economics", 
            "Business Management And Administration", 
            "Chemical Engineering", 
            "Chemistry", 
            "Civil Engineering", 
            "Clinical Psychology", 
            "Cognitive Science And Biopsychology", 
            "Commercial Art And Graphic Design", 
            "Communication Disorders Sciences And Services", 
            "Communication Technologies", 
            "Communications", 
            "Community And Public Health", 
            "Composition And Rhetoric", 
            "Computer Administration Management And Security", 
            "Computer And Information Systems", 
            "Computer Engineering", 
            "Computer Networking And Telecommunications", 
            "Computer Programming And Data Processing", 
            "Computer Science", 
            "Construction Services", 
            "Cosmetology Services And Culinary Arts", 
            "Counseling Psychology", 
            "Court Reporting", 
            "Criminal Justice And Fire Protection", 
            "Criminology", 
            "Drama And Theater Arts", 
            "Early Childhood Education", 
            "Ecology", 
            "Economics", 
            "Educational Administration And Supervision", 
            "Educational Psychology", 
            "Electrical Engineering", 
            "Electrical Engineering Technology", 
            "Electrical, 
            Mechanical, 
            And Precision Technologies And Production", 
            "Elementary Education", 
            "Engineering And Industrial Management", 
            "Engineering Mechanics Physics And Science", 
            "Engineering Technologies", 
            "English Language And Literature", 
            "Environmental Engineering", 
            "Environmental Science", 
            "Family And Consumer Sciences", 
            "Film Video And Photographic Arts", 
            "Finance", 
            "Fine Arts", 
            "Food Science", 
            "Forestry", 
            "French German Latin And Other Common Foreign Language Studies", 
            "General Agriculture", 
            "General Business", 
            "General Education", 
            "General Engineering", 
            "General Medical And Health Services", 
            "General Social Sciences", 
            "Genetics", 
            "Geography", 
            "Geological And Geophysical Engineering", 
            "Geology And Earth Science", 
            "Geosciences", 
            "Health And Medical Administrative Services", 
            "Health And Medical Preparatory Programs", 
            "History", 
            "Hospitality Management", 
            "Human Resources And Personnel Management", 
            "Human Services And Community Organization", 
            "Humanities", 
            "Industrial And Manufacturing Engineering", 
            "Industrial And Organizational Psychology", 
            "Industrial Production Technologies", 
            "Information Sciences", 
            "Intercultural And International Studies", 
            "Interdisciplinary Social Sciences", 
            "International Business", 
            "International Relations", 
            "Journalism", 
            "Language And Drama Education", 
            "Liberal Arts", 
            "Library Science", 
            "Linguistics And Comparative Language And Literature", 
            "Management Information Systems And Statistics", 
            "Marketing And Marketing Research", 
            "Mass Media", 
            "Materials Engineering And Materials Science", 
            "Materials Science", 
            "Mathematics", 
            "Mathematics And Computer Science", 
            "Mathematics Teacher Education", 
            "Mechanical Engineering", 
            "Mechanical Engineering Related Technologies", 
            "Medical Assisting Services", 
            "Medical Technologies Technicians", 
            "Metallurgical Engineering", 
            "Microbiology", 
            "Military Technologies", 
            "Mining And Mineral Engineering", 
            "Miscellaneous Agriculture", 
            "Miscellaneous Biology", 
            "Miscellaneous Business & Medical Administration", 
            "Miscellaneous Education", 
            "Miscellaneous Engineering", 
            "Miscellaneous Engineering Technologies", 
            "Miscellaneous Fine Arts", 
            "Miscellaneous Health Medical Professions", 
            "Miscellaneous Psychology", 
            "Miscellaneous Social Sciences", 
            "Molecular Biology", 
            "Multi-Disciplinary Or General Science", 
            "Multi/Interdisciplinary Studies", 
            "Music", 
            "N/A (Less Than Bachelor'S Degree)", 
            "Natural Resources Management", 
            "Naval Architecture And Marine Engineering", 
            "Neuroscience", 
            "Nuclear Engineering", 
            "Nuclear, 
            Industrial Radiology, 
            And Biological Technologies", 
            "Nursing", 
            "Nutrition Sciences", 
            "Oceanography", 
            "Operations Logistics And E-Commerce", 
            "Other Foreign Languages", 
            "Petroleum Engineering", 
            "Pharmacology", 
            "Pharmacy Pharmaceutical Sciences And Administration", 
            "Philosophy And Religious Studies", 
            "Physical And Health Education Teaching", 
            "Physical Fitness Parks Recreation And Leisure", 
            "Physical Sciences", 
            "Physics", 
            "Physiology", 
            "Plant Science And Agronomy", 
            "Political Science And Government", 
            "Pre-Law And Legal Studies", 
            "Psychology", 
            "Public Administration", 
            "Public Policy", 
            "School Student Counseling", 
            "Science And Computer Teacher Education", 
            "Secondary Teacher Education", 
            "Social Psychology", 
            "Social Science Or History Teacher Education", 
            "Social Work", 
            "Sociology", 
            "Soil Science", 
            "Special Needs Education", 
            "Statistics And Decision Science", 
            "Studio Arts", 
            "Teacher Education: Multiple Levels", 
            "Theology And Religious Vocations", 
            "Transportation Sciences And Technologies", 
            "Treatment Therapy Professions", 
            "United States History", 
            "Visual And Performing Arts", 
            "Zoology"
        ];

        foreach ($courses as $course) {
            Course::create(['course' => $course]);
        }
    }
}
